-- Campos: área jurídica, foto do reclamante e documento anexo
ALTER TABLE planilha1
    ADD COLUMN IF NOT EXISTS AREA VARCHAR(30) NULL AFTER CPF,
    ADD COLUMN IF NOT EXISTS FOTO LONGBLOB NULL,
    ADD COLUMN IF NOT EXISTS FOTO_TIPO VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS DOCUMENTO LONGBLOB NULL,
    ADD COLUMN IF NOT EXISTS DOCUMENTO_NOME VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS DOCUMENTO_TIPO VARCHAR(100) NULL;
