-- MySQL — Moura Galvão · Sistema de Processos
-- Execute no phpMyAdmin ou: mysql -u root -p < schema_mysql.sql

CREATE DATABASE IF NOT EXISTS advocacia
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE advocacia;

CREATE TABLE IF NOT EXISTS planilha1 (
    CADASTRO          INT NOT NULL,
    RECLAMANTE        VARCHAR(500)  NULL,
    DATA_NASC         VARCHAR(50)   NULL,
    ENDERE_O          VARCHAR(500)  NULL,
    FONE_RTE          VARCHAR(100)  NULL,
    FONE_RTE_2_       VARCHAR(100)  NULL,
    FONE_RTE_3_       VARCHAR(100)  NULL,
    FONE_RTE_4_       VARCHAR(100)  NULL,
    FALAR_COM_FONE_1_ VARCHAR(200)  NULL,
    FALAR_COM_FONE_2_ VARCHAR(200)  NULL,
    FALAR_COM_FONE_3_ VARCHAR(200)  NULL,
    FALAR_COM_FONE_4_ VARCHAR(200)  NULL,
    RECLAMADA         VARCHAR(500)  NULL,
    END_RDA           VARCHAR(500)  NULL,
    JUNTA             VARCHAR(50)   NULL,
    `PROC`            VARCHAR(100)  NULL,
    DIA_AUD           VARCHAR(50)   NULL,
    HORA_AUD          VARCHAR(50)   NULL,
    PRA_A_DIA         VARCHAR(50)   NULL,
    PRA_A_HORA        VARCHAR(50)   NULL,
    ANDAMENTO         TEXT          NULL,
    CTPS              VARCHAR(100)  NULL,
    IDENTIDADE        VARCHAR(100)  NULL,
    CPF               VARCHAR(20)   NULL,
    AREA              VARCHAR(30)   NULL,
    FOTO              LONGBLOB      NULL,
    FOTO_TIPO         VARCHAR(50)   NULL,
    DOCUMENTO         LONGBLOB      NULL,
    DOCUMENTO_NOME    VARCHAR(255)  NULL,
    DOCUMENTO_TIPO    VARCHAR(100)  NULL,
    COL_2__RECLAMADA  VARCHAR(500)  NULL,
    END_RDA_1         VARCHAR(500)  NULL,
    cxpra_a           VARCHAR(100)  NULL,
    PRIMARY KEY (CADASTRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_reclamante ON planilha1 (RECLAMANTE(191));
CREATE INDEX idx_reclamada  ON planilha1 (RECLAMADA(191));
CREATE INDEX idx_proc       ON planilha1 (`PROC`(100));

CREATE TABLE IF NOT EXISTS pericias (
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    CADASTRO      INT           NULL,
    DATA_PERICIA  VARCHAR(50)   NULL,
    HORA_PERICIA  VARCHAR(50)   NULL,
    RECLAMANTE    VARCHAR(500)  NULL,
    CPF           VARCHAR(20)   NULL,
    RECLAMADA     VARCHAR(500)  NULL,
    PROC_NUM      VARCHAR(100)  NULL,
    NOME_PERITO   VARCHAR(255)  NULL,
    ENDERECO      TEXT          NULL,
    ORIGEM        VARCHAR(20)   NOT NULL DEFAULT 'cadastro',
    CRIADO_EM     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_pericias_cadastro (CADASTRO),
    INDEX idx_pericias_data (DATA_PERICIA(20)),
    INDEX idx_pericias_origem (ORIGEM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuarios (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN       VARCHAR(50)  NOT NULL,
    SENHA_HASH  VARCHAR(255) NOT NULL,
    NOME        VARCHAR(100) NOT NULL,
    IS_ADMIN    TINYINT(1)   NOT NULL DEFAULT 0,
    ATIVO       TINYINT(1)   NOT NULL DEFAULT 1,
    CRIADO_EM   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_usuarios_login (LOGIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuario_permissoes (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID  INT          NOT NULL,
    MODULO      VARCHAR(50)  NOT NULL,
    PODE_VER    TINYINT(1)   NOT NULL DEFAULT 0,
    PODE_EDITAR TINYINT(1)   NOT NULL DEFAULT 0,
    UNIQUE KEY uk_usuario_modulo (USUARIO_ID, MODULO),
    INDEX idx_perm_usuario (USUARIO_ID),
    CONSTRAINT fk_perm_usuario FOREIGN KEY (USUARIO_ID)
        REFERENCES usuarios (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS log_atividades (
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID    INT           NULL,
    USUARIO_LOGIN VARCHAR(50)   NULL,
    USUARIO_NOME  VARCHAR(100)  NULL,
    ACAO          VARCHAR(50)   NOT NULL,
    MODULO        VARCHAR(50)   NULL,
    REFERENCIA    VARCHAR(100)  NULL,
    DESCRICAO     TEXT          NOT NULL,
    DETALHES      TEXT          NULL,
    IP            VARCHAR(45)   NULL,
    CRIADO_EM     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_log_data (CRIADO_EM),
    INDEX idx_log_usuario (USUARIO_ID),
    INDEX idx_log_acao (ACAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
